# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstServed' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  
  # Pods for FirstServed

  target 'FirstServed-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirstServedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge',
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  [
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging'
].each do |lib|
  pod lib
end
post_install do
  `rm -rf Pods/leveldb-library/port/win`
end
